name: Coins-System
main: me.size.CoinSystem
version: ${project.version}
authors: [size]
commands:
  coins:
    usage: /<command> | /<command> <player>
    description: Get Coins of a Player (Online only!)
  addcoins:
    usage: /<command> <player> <amount>
    description: Add Coins to a Player
  setcoins:
    usage: /<command> <player> <amount>
    description: Set Coins of a Player
  removecoins:
    usage: /<command> <player> <amount>
    description: Remove a amount of Coins of a Player
  pay:
    usage: /<command> <player> <amount>
    description: Pay Coins to other Players